homeassistant:
  # Name of the location where Home Assistant is running
  name: Cervera's Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 5
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
 # DEV BETA Sensor temp from Daikin HVAC
  - platform: command_line
    name: In
    command: curl --data "id=&spw=&por" http://192.168.11.213/aircon/get_sensor_info | grep -oP '(?<=htemp\=).*(?=,hhum)'
    unit_of_measurement: "°C"
    interval: 600   
  - platform: command_line
    name: Out
    command: curl --data "id=&spw=&por" http://192.168.11.213/aircon/get_sensor_info | grep -oP '(?<=otemp\=).*(?=,err)'
    unit_of_measurement: "°C" 
    interval: 300
# Text to speech
tts:
  platform: google

# Webcams
camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.11.90/mjpg/video.mjpg
    name: ccam

# Device tracking
device_tracker:
  - platform: ddwrt
    host: 192.168.11.1
    username: root
    password: !secret router_password
    name: router

media_player:
# Squeezebox Radio kan inte kontrolleras via telnet/ssh...
#  - platform: squeezebox
#    host: 192.168.11.225
#    port: 22
#    user: 
#    password:
